previewsEnabled: false
databases:
  - name: seadev-db
    databaseName: seadev_db
    plan: free

services:
  # A Docker web service
  # Docs for Render blueprints:
  # https://render.com/docs/blueprint-spec
  - type: web
    name: seadev-backend
    runtime: docker
    repo: https://github.com/seadotdev/pdf-insight.git
    region: frankfurt
    plan: free
    rootDir: ./backend
    scaling:
      minInstances: 1
      targetMemoryPercent: 75 # optional if targetCPUPercent is set (valid: 1-90)
      targetCPUPercent: 75 # optional if targetMemory is set (valid: 1-90)
    healthCheckPath: /api/health/
    # initialDeployHook: make seed_db_based_on_env
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: seadev-db
          property: connectionString
      - fromGroup: general-settings
      - fromGroup: prod-web-secrets
      - fromGroup: preview-web-secrets
envVarGroups:
- name: general-settings
  envVars:
    - key: LOG_LEVEL
      value: INFO
    - key: BACKEND_CORS_ORIGINS
      value: '["http://localhost", "http://localhost:8000", "http://localhost:3000", "http://127.0.0.1:3000", "https://app.sea.dev"]'
    # S3_BUCKET_NAME is the bucket used for the StorageContext of the backend's LlamaIndex chat engine
    - key: S3_BUCKET_NAME
      value: seadev-backend-prod
    # S3_ASSET_BUCKET_NAME is the bucket used for app assets (e.g. document PDFs)
    - key: S3_ASSET_BUCKET_NAME
      value: seadev-assets-prod
    - key: CDN_BASE_URL
      value: https://d687lz8k56fia.cloudfront.net
    - key: SENTRY_DSN
      value: https://eba501c8450c42b0bbd2eb9467224e22@o4505586322833408.ingest.sentry.io/4505592019222528
- name: prod-web-secrets
  envVars:
    # Manually add a prod value for OPENAI_API_KEY in Render dashboard
    - key: OPENAI_API_KEY
      sync: false
    - key: AWS_KEY
      sync: false
    - key: AWS_SECRET
      sync: false
    - key: POLYGON_IO_API_KEY
      sync: false
